# Site settings
title: Clintko's Blog
description: "Biology, Data, Cocktail, and Violin"
url: "https://clintko.github.io/blog/"
author:
  name: "Clintko"
  email: "clint00724@gmail.com"
  url: "https://clintko.github.io/blog//about"

# Build settings
baseurl: /blog/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: true
reverse: false

# generate sitemap.xml
#gems:
#  - jekyll-sitemap
  
gems:
  - jekyll-paginate
